### ISSUE TITLE
Figure out datanucleus exceptions

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.persistence#21]
- [x] javax.jdo.JDOObjectNotFoundException: No such database row - Happens sometimes when persisting a project, see full stack in comment
- [x] Object with id "org.geppetto.persistence.db.model.User@5abb2427" is managed by a different persistence manager - Happens sometimes when saving a project (whether it's persisting or saving a project)
- [x] Exception in thread "Thread-71" java.lang.NullPointerException at org.geppetto.persistence.db.model.InstancePath.dnGetinstancePath(InstancePath.java) - Happens randomly when running thrown by ExperimentRunThread at line 289 dnGetInstancePath is a method added by the enhancement
- [x] Could not delete data javax.jdo.JDODataStoreException: Exception thrown flushing changes to datastore. Happened when deleting an experiment

**Comment by tarelli** [comment]
```
javax.jdo.JDOObjectNotFoundException: No such database row
	at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:567)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:725)
	at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:745)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.orm.jdo.TransactionAwarePersistenceManagerFactoryProxy$PersistenceManagerInvocationHandler.invoke(TransactionAwarePersistenceManagerFactoryProxy.java:211)
	at com.sun.proxy.$Proxy106.makePersistent(Unknown Source)
	at org.geppetto.persistence.db.DBManager.storeEntity(DBManager.java:71)
	at org.geppetto.persistence.GeppettoDataManager.addGeppettoProject(GeppettoDataManager.java:279)
```

**Comment by tarelli** [comment]
```
[2015-10-14 17:04:56.819] INFO http-bio-8080-exec-18 DataNucleus.JDO Exception thrown org.datanucleus.exceptions.NucleusUserException: Object with id "org.geppetto.persistence.db.model.User@5abb2427" is managed by a different persistence manager
at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:1905)
at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1843)
at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1706)
at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:720)
at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:745)
at sun.reflect.GeneratedMethodAccessor121.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.springframework.orm.jdo.TransactionAwarePersistenceManagerFactoryProxy$PersistenceManagerInvocationHandler.invoke(TransactionAwarePersistenceManagerFactoryProxy.java:211)
at com.sun.proxy.$Proxy101.makePersistent(Unknown Source)
at org.geppetto.persistence.db.DBManager.storeEntity(DBManager.java:71)
at org.geppetto.persistence.GeppettoDataManager.addGeppettoProject(GeppettoDataManager.java:275)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:131)
at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:119)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
at com.sun.proxy.$Proxy89.addGeppettoProject(Unknown Source)
at org.geppetto.frontend.controllers.GeppettoManager.persistProject(GeppettoManager.java:266)
at org.geppetto.frontend.controllers.ConnectionHandler.persistProject(ConnectionHandler.java:861)
at org.geppetto.frontend.controllers.WebsocketConnection.onTextMessage(WebsocketConnection.java:225)
at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:78)
at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:191)
at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:139)
at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:88)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by tarelli** [comment]
```
Exception thrown org.datanucleus.exceptions.NucleusUserException: Object with id "org.geppetto.persistence.db.model.GeppettoProject@2d7a2d72" is managed by a different persistence manager
	at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:1905)
	at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1843)
	at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1706)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:720)
	at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:745)
	at sun.reflect.GeneratedMethodAccessor181.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.orm.jdo.TransactionAwarePersistenceManagerFactoryProxy$PersistenceManagerInvocationHandler.invoke(TransactionAwarePersistenceManagerFactoryProxy.java:211)
	at com.sun.proxy.$Proxy106.makePersistent(Unknown Source)
	at org.geppetto.persistence.db.DBManager.storeEntity(DBManager.java:71)
	at org.geppetto.persistence.GeppettoDataManager.saveEntity(GeppettoDataManager.java:397)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:131)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy93.saveEntity(Unknown Source)
	at org.geppetto.simulation.manager.ExperimentRunThread.run(ExperimentRunThread.java:311)
```

**Comment by gidili** [comment]
```ERROR http-bio-8080-exec-12        org.geppetto.frontend.controllers.ConnectionHandler               Unable to link dropbox account. javax.jdo.JDOObjectNotFoundException: No such database row
	at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:567)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:725)
	at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:745)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.springframework.orm.jdo.TransactionAwarePersistenceManagerFactoryProxy$PersistenceManagerInvocationHandler.invoke(TransactionAwarePersistenceManagerFactoryProxy.java:211)
	at com.sun.proxy.$Proxy98.makePersistent(Unknown Source)
	at org.geppetto.persistence.db.DBManager.storeEntity(DBManager.java:71)
	at org.geppetto.persistence.GeppettoDataManager.saveEntity(GeppettoDataManager.java:384)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:131)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy95.saveEntity(Unknown Source)
	at org.geppetto.simulation.manager.GeppettoManager.linkDropBoxAccount(GeppettoManager.java:421)
	at org.geppetto.frontend.controllers.ConnectionHandler.linkDropBox(ConnectionHandler.java:795)
	at org.geppetto.frontend.controllers.WebsocketConnection.onTextMessage(WebsocketConnection.java:360)
	at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:74)
	at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:186)
	at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:134)
	at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
Caused by: org.datanucleus.exceptions.NucleusObjectNotFoundException: No such database row
	at org.datanucleus.store.rdbms.request.FetchRequest.execute(FetchRequest.java:359)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.fetchObject(RDBMSPersistenceHandler.java:319)
	at org.datanucleus.state.AbstractStateManager.loadFieldsFromDatastore(AbstractStateManager.java:1147)
	at org.datanucleus.state.StateManagerImpl.attachCopy(StateManagerImpl.java:4141)
	at org.datanucleus.state.StateManagerImpl.attachCopy(StateManagerImpl.java:117)
	at org.datanucleus.ExecutionContextImpl.attachObjectCopy(ExecutionContextImpl.java:2565)
	at org.datanucleus.store.types.SCOUtils.attachCopyForCollection(SCOUtils.java:676)
	at org.datanucleus.store.types.wrappers.List.attachCopy(List.java:206)
	at org.datanucleus.store.types.wrappers.List.attachCopy(List.java:41)
	at org.datanucleus.store.fieldmanager.AttachFieldManager.storeObjectField(AttachFieldManager.java:224)
	at org.datanucleus.state.AbstractStateManager.providedObjectField(AbstractStateManager.java:1460)
	at org.datanucleus.state.StateManagerImpl.providedObjectField(StateManagerImpl.java:117)
	at org.geppetto.persistence.db.model.GeppettoProject.dnProvideField(GeppettoProject.java)
	at org.geppetto.persistence.db.model.GeppettoProject.dnProvideFields(GeppettoProject.java)
	at org.datanucleus.state.StateManagerImpl.provideFields(StateManagerImpl.java:1174)
	at org.datanucleus.state.StateManagerImpl.internalAttachCopy(StateManagerImpl.java:4241)
	at org.datanucleus.state.StateManagerImpl.attachCopy(StateManagerImpl.java:4190)
	at org.datanucleus.state.StateManagerImpl.attachCopy(StateManagerImpl.java:117)
	at org.datanucleus.ExecutionContextImpl.attachObjectCopy(ExecutionContextImpl.java:2565)
	at org.datanucleus.store.types.SCOUtils.attachCopyForCollection(SCOUtils.java:676)
	at org.datanucleus.store.types.wrappers.List.attachCopy(List.java:206)
	at org.datanucleus.store.types.wrappers.List.attachCopy(List.java:41)
	at org.datanucleus.store.fieldmanager.AttachFieldManager.storeObjectField(AttachFieldManager.java:224)
	at org.datanucleus.state.AbstractStateManager.providedObjectField(AbstractStateManager.java:1460)
	at org.datanucleus.state.StateManagerImpl.providedObjectField(StateManagerImpl.java:117)
	at org.geppetto.persistence.db.model.User.dnProvideField(User.java)
	at org.geppetto.persistence.db.model.User.dnProvideFields(User.java)
	at org.datanucleus.state.StateManagerImpl.provideFields(StateManagerImpl.java:1174)
	at org.datanucleus.state.StateManagerImpl.internalAttachCopy(StateManagerImpl.java:4241)
	at org.datanucleus.state.StateManagerImpl.attachCopy(StateManagerImpl.java:4190)
	at org.datanucleus.state.StateManagerImpl.attachCopy(StateManagerImpl.java:117)
	at org.datanucleus.ExecutionContextImpl.attachObjectCopy(ExecutionContextImpl.java:2565)
	at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:1917)
	at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1843)
	at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1706)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:720)
	... 33 common frames omitted
```

**Comment by tarelli** [comment]
```
Exception in thread "Thread-71" java.lang.NullPointerException 
[2016-02-12 15:51:25.420] ERROR Thread-71                    System.err                                                        	at org.geppetto.persistence.db.model.InstancePath.dnGetinstancePath(InstancePath.java) 
[2016-02-12 15:51:25.421] ERROR Thread-71                    System.err                                                        	at org.geppetto.persistence.db.model.InstancePath.getInstancePath(InstancePath.java:33) 
[2016-02-12 15:51:25.421] ERROR Thread-71                    System.err                                                        	at org.geppetto.simulation.manager.ExperimentRunThread.run(ExperimentRunThread.java:289) 

```

**Comment by tarelli** [comment]
```
Could not delete data javax.jdo.JDODataStoreException: Exception thrown flushing changes to datastore
	at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:546)
	at org.datanucleus.api.jdo.JDOTransaction.commit(JDOTransaction.java:171)
	at org.geppetto.persistence.db.DBManager.deleteEntity(DBManager.java:197)
	at org.geppetto.persistence.GeppettoDataManager.deleteExperiment(GeppettoDataManager.java:316)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:131)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy93.deleteExperiment(Unknown Source)
	at org.geppetto.simulation.manager.GeppettoManager.deleteExperiment(GeppettoManager.java:397)
	at org.geppetto.frontend.controllers.ConnectionHandler.deleteExperiment(ConnectionHandler.java:701)
	at org.geppetto.frontend.controllers.WebsocketConnection.onTextMessage(WebsocketConnection.java:289)
	at org.apache.catalina.websocket.MessageInbound.onTextData(MessageInbound.java:78)
	at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:191)
	at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:139)
	at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:88)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Cannot delete or update a parent row: a foreign key constraint fails (`geppetto`.`geppettoproject_experiments`, CONSTRAINT `GEPPETTOPROJECT_EXPERIMENTS_FK2` FOREIGN KEY (`ID_EID`) REFERENCES `EXPERIMENT` (`ID`))
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1666)
	at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1082)
	at org.datanucleus.store.rdbms.datasource.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:279)
	at org.datanucleus.store.rdbms.datasource.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:279)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeBatch(ParamLoggingPreparedStatement.java:366)
	at org.datanucleus.store.rdbms.SQLController.processConnectionStatement(SQLController.java:676)
	at org.datanucleus.store.rdbms.SQLController.processStatementsForConnection(SQLController.java:644)
	at org.datanucleus.store.rdbms.SQLController$1.transactionFlushed(SQLController.java:731)
	at org.datanucleus.store.connection.AbstractManagedConnection.transactionFlushed(AbstractManagedConnection.java:89)
	at org.datanucleus.store.connection.ConnectionManagerImpl$2.transactionFlushed(ConnectionManagerImpl.java:450)
	at org.datanucleus.TransactionImpl.flush(TransactionImpl.java:212)
	at org.datanucleus.TransactionImpl.commit(TransactionImpl.java:276)
	at org.datanucleus.api.jdo.JDOTransaction.commit(JDOTransaction.java:107)

```

**Comment by tarelli** [comment]
@gidili @adrianq I have made some changes to do with multi thread, including discovering a datanucleus option that would make it thread safe. They seem to be all gone, all gone now.

**Comment by tarelli** [comment]
@adrianq @gidili reopen if you see any of the above in the future.

**Comment by jrmartin** [comment]
I ran into these errors while using latest persistence bundle code, looking into them now.

**Comment by jrmartin** [comment]
Issues gone now when doing delete.

**Comment by slarson** [comment]
The fix is in Should be closed in https://github.com/openworm/org.geppetto.persistence/tree/experiments_table_refactoring -- new tests in https://github.com/openworm/org.geppetto.persistence/blob/experiments_table_refactoring/src/test/java/org/geppetto/persistence/db/DBManagerTest.java appear to cover this.
